language: ruby

rvm:
  - 2.2

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - bundle install

addons:
  firefox: "40.0"

script: rspec ./spec/automation_task_spec.rb